# Generated by Django 5.2.13 on 2026-04-22 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('journal', models.CharField(blank=True, default='', max_length=500)),
                ('journal_type', models.CharField(choices=[('scopus', 'Scopus'), ('wos', 'Web of Science'), ('vak', 'ВАК'), ('rinc', 'РИНЦ'), ('other', 'Прочее')], max_length=10)),
                ('pub_date', models.DateField()),
                ('url', models.CharField(blank=True, default='', max_length=2048)),
                ('coauthors', models.TextField(blank=True, default='')),
                ('evidence_file', models.CharField(blank=True, default='', max_length=500)),
                ('is_archived', models.BooleanField(default=False)),
                ('academic_year', models.CharField(max_length=10)),
                ('kpi_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='kpi.kpi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-pub_date', '-created_at'],
            },
        ),
    ]
