# Generated by Django 5.2.13 on 2026-04-22 09:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('weight', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Показатель КПЭ',
                'verbose_name_plural': 'Показатели КПЭ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KPIResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('period_type', models.CharField(choices=[('month', 'Month'), ('semester', 'Semester'), ('year', 'Year')], max_length=10)),
                ('period_value', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат КПЭ',
                'verbose_name_plural': 'Результаты КПЭ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('period_type', models.CharField(choices=[('month', 'Month'), ('semester', 'Semester'), ('year', 'Year')], max_length=10)),
                ('period_value', models.CharField(max_length=20)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='kpi.kpi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Значение КПЭ',
                'verbose_name_plural': 'Значения КПЭ',
                'ordering': ['-created_at'],
            },
        ),
    ]
