# Generated by Django 5.2.13 on 2026-04-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='category',
            field=models.CharField(choices=[('science', 'Наука'), ('teaching', 'Учебная работа'), ('methodology', 'Методическая работа'), ('education', 'Воспитательная работа'), ('load', 'Нагрузка'), ('other', 'Прочее')], default='other', max_length=20),
        ),
    ]
