# Generated by Django 5.2.13 on 2026-04-22 10:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('academic_year', models.CharField(max_length=10)),
                ('semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('target_hours', models.IntegerField()),
                ('actual_hours', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='departments.department')),
            ],
            options={
                'verbose_name': 'Нагрузка кафедры',
                'verbose_name_plural': 'Нагрузки кафедр',
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('department', 'academic_year', 'semester')},
            },
        ),
    ]
