# Generated by Django 5.2.13 on 2026-04-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department_user_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Админ'), (1, 'Ректор'), (2, 'Проректор'), (3, 'Научный отдел'), (4, 'Отдел по делам студентов'), (5, 'Декан'), (6, 'Заведующий кафедрой'), (7, 'Учитель')], default=7),
        ),
    ]
